/** Theme tokens extracted verbatim from visual.html (OrbitGuard Mission Control). */
/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#0d1c2d",
        secondary: "#b9c7e0",
        "surface-tint": "#bec6e0",
        "surface-bright": "#2c3a4c",
        "surface-container-highest": "#273647",
        "on-primary-fixed": "#131b2e",
        "secondary-container": "#3c4a5e",
        "primary-fixed": "#dae2fd",
        "on-surface-variant": "#c6c6cd",
        "on-error": "#690005",
        "terminal-cyan": "#22D3EE",
        "on-secondary-fixed": "#0d1c2f",
        "tertiary-container": "#001c10",
        "on-primary": "#283044",
        "primary-fixed-dim": "#bec6e0",
        "inverse-on-surface": "#233143",
        "secondary-fixed": "#d5e3fd",
        "secondary-fixed-dim": "#b9c7e0",
        "inverse-primary": "#565e74",
        primary: "#bec6e0",
        "on-background": "#d4e4fa",
        "on-secondary": "#233144",
        "risk-critical": "#EF4444",
        "space-gray-deep": "#1E293B",
        "error-container": "#93000a",
        "surface-container-lowest": "#010f1f",
        "on-tertiary-container": "#009365",
        "on-tertiary-fixed": "#002113",
        "on-tertiary": "#003824",
        "on-primary-container": "#798098",
        "on-secondary-fixed-variant": "#3a485c",
        "on-tertiary-fixed-variant": "#005236",
        error: "#ffb4ab",
        background: "#051424",
        "on-error-container": "#ffdad6",
        "risk-low": "#10B981",
        "primary-container": "#0f172a",
        "inverse-surface": "#d4e4fa",
        "risk-moderate": "#FBBF24",
        tertiary: "#4edea3",
        surface: "#051424",
        "surface-dim": "#051424",
        "surface-container": "#122131",
        "risk-high": "#F97316",
        outline: "#909097",
        "surface-container-high": "#1c2b3c",
        "on-surface": "#d4e4fa",
        "surface-variant": "#273647",
        "on-primary-fixed-variant": "#3f465c",
        "tertiary-fixed-dim": "#4edea3",
        "on-secondary-container": "#abb9d2",
        "tertiary-fixed": "#6ffbbe",
        "outline-variant": "#45464d",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-md": "24px",
        "panel-padding": "16px",
        "margin-lg": "40px",
        base: "4px",
        gutter: "16px",
        "margin-sm": "12px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
